services:

    #
    # Generators
    #
    visithor.url_generator:
        class: Visithor\Bundle\Generator\SymfonyUrlGenerator
        arguments:
            - "@visithor.factory.url"
            - "@visithor.factory.url_chain"
            - "@router"
