language: php

env:
    - COMPOSER_OPTIONS="--prefer-source"

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: COMPOSER_OPTIONS="--prefer-lowest"

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

script:
    - bin/phpunit

notifications:
    email: false
